# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='videoentry',
            name='feedback',
        ),
        migrations.AddField(
            model_name='videoentry',
            name='feedbackTable',
            field=models.ManyToManyField(to='upload.Feedback'),
        ),
    ]
