# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190518_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoentry',
            name='processedVideoPath',
            field=models.CharField(default='', max_length=300),
        ),
    ]
