# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_videoentry_processedvideopath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoentry',
            old_name='feedbackTable',
            new_name='feedback',
        ),
    ]
